### ISSUE TITLE
Give a description of available data for a given concept

### ISSUE THREAD

**Issue by grlurton** [grlurton/dhisextractr#4]
Use case is time of exploration of a DHIS implementation. We want to be able to know, for a given concept:

1. What Data elements are available
2. Which facility have been reporting most on it / which zone / which org_unit grouping
3. What are the periods with most report on it

As a result we want to create a formal descriptive for users to be able to understand what data they can expect on a given topic

**Comment by romainolekhnovitch** [comment]
Can we agree on some specific indicators that we would like to be displayed (input is a given concept, e.g., "hiv")
1) List of data elements available (should be case insensitive)
2) reporting rate by region & by org_unit grouping (I suggest we go with the "report at least once during the year" metric for each facility)
3) ok
4) I would add a typical distribution metric (mean of the DE per region --> display figures for all regions)

**Comment by grlurton** [comment]
1. ok, this is already working
2. I'd rather do _n reported_ / _n expected_ in the extracted data window as this window may be yearly. And _n expected_ = _time window_ / _report periodicity_ . For data extraction windows larger than a year, we could do this for the last 12 months only ? 
4. Yes. one pb is the comparability across units / region, would need to find a way to normalize ?

**Comment by romainolekhnovitch** [comment]
2. ok for me
4. (I think you were referring to this one) I think using a metric per facility --> (e.g. "mean number of HIV+ patients monitored in a HF) + using a metric at the region level (total number of HIV+ patients monitored in the region)

**Comment by grlurton** [comment]
Closed. should be moved in different specific issues. aggregation work is currently taking care of 2 and 3

@romainolekhnovitch  on veut toujours faire 4. dans le cadre de dhisextractr ?
